@startuml
class ClaseInscrita {
    + ClaseInscrita()
    + ClaseInscrita(claseDeportivaId:int, inscripcionId:int, plazasReservadas:int, precio:decimal, observaciones:string?)
    + Id : int <<get>> <<set>>
    + ClaseDeportivaId : int <<get>> <<set>>
    + InscripcionId : int <<get>> <<set>>
    + Observaciones : string? <<get>> <<set>>
    + PlazasReservadas : int <<get>> <<set>>
    + Precio : decimal <<get>> <<set>>
    + Inscripcion : Inscripcion <<get>> <<set>>
    + ClaseDeportiva : ClaseDeportiva <<get>> <<set>>
}

ClaseInscrita "*" --> "1" Inscripcion : Inscripcion
ClaseInscrita "*" --> "1" ClaseDeportiva : ClaseDeportiva
@enduml
