@startuml
class ClaseDeportiva {
    + ClaseDeportiva()
    + ClaseDeportiva(descripcion:string, fechaHora:DateTime, monitor:string, nivel:string, plazasDisponibles:int, precioUnitario:decimal, tipoDeporteId:int, lugar:string?)
    + Id : int <<get>> <<set>>
    + Descripcion : string <<get>> <<set>>
    + FechaHora : DateTime <<get>> <<set>>
    + Lugar : string? <<get>> <<set>>
    + Monitor : string <<get>> <<set>>
    + Nivel : string <<get>> <<set>>
    + PlazasDisponibles : int <<get>> <<set>>
    + PrecioUnitario : decimal <<get>> <<set>>
    + TipoDeporteId : int <<get>> <<set>>
    + TipoDeporte : TipoDeporte <<get>> <<set>>
    + ClasesInscritas : IList<ClaseInscrita> <<get>> <<set>>
}

ClaseDeportiva "*" --> "1" TipoDeporte : TipoDeporte
ClaseDeportiva "1" --> "*" ClaseInscrita : ClasesInscritas
@enduml
