@startuml
class CompeticionInscrita {
    + Id : int <<get>> <<set>>
    + CompeticionId : int <<get>> <<set>>
    + InscripcionId : int <<get>> <<set>>
    + ProblemasFisicos : string? <<get>> <<set>>
    + Inscripcion : Inscripcion <<get>> <<set>>
    + Competicion : Competicion <<get>> <<set>>
}
@enduml
