@startuml
!include .\\Competicion.puml
!include .\\CompeticionInscrita.puml
!include .\\Inscripcion.puml
!include .\\TipoDeporte.puml

hide ClaseDeportiva
hide ClaseInscrita
hide ApplicationUser
@enduml