@startuml
!include .\\.\Models\ApplicationUser.puml
!include .\\.\Models\ClaseDeportiva.puml
!include .\\.\Models\ClaseInscrita.puml
!include .\\.\Models\Competicion.puml
!include .\\.\Models\CompeticionInscrita.puml
!include .\\.\Models\Inscripcion.puml
!include .\\.\Models\MetodoPago.puml
!include .\\.\Models\Pista.puml
!include .\\.\Models\TipoDeporte.puml
@enduml
