@startuml
class Inscripcion {
    + Inscripcion()
    + Inscripcion(nombreUsuario:string, apellidosUsuario:string, dni:string, telefono:string, fechaInscripcion:DateTime, metodoPago:MetodoPago, precioTotal:decimal, datosPago:string)
    + Id : int <<get>> <<set>>
    + NombreUsuario : string <<get>> <<set>>
    + ApellidosUsuario : string <<get>> <<set>>
    + DNI : string <<get>> <<set>>
    + Telefono : string <<get>> <<set>>
    + FechaInscripcion : DateTime <<get>> <<set>>
    + MetodoPago : MetodoPago <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + DatosPago : string <<get>> <<set>>
    + CompeticionesInscritas : IList<CompeticionInscrita> <<get>> <<set>>
    + Cliente : ApplicationUser <<get>> <<set>>
    + ClasesInscritas : IList<ClaseInscrita> <<get>> <<set>>
}

Inscripcion "*" --> "1" ApplicationUser : Cliente
Inscripcion "*" --> "1" MetodoPago : MetodoPago
@enduml
