@startuml
hide methods
skinparam classAttributeIconSize 0

class TipoDeporte {
  + Id : int
  + Nombre : string
}

class Pista {
  + IdPista : int
  + NombrePista : string
  + NPersonas : int
  + Precio : decimal
  + Stock : int
  + IdTipoDeporte : int
}

class PistaReservada {
  + Id : int
  + Cantidad : int
  + Precio : decimal
  + Observaciones : string
  + IdPista : int
  + IdReserva : int
}

class Reserva {
  + Id : int
  + NombreCliente : string
  + Apellidos : string
  + Dni : string
  + FechaReserva : DateTime
  + MetodoPago : MetodoPago
  + PrecioTotal : decimal
}

enum MetodoPago {
  Bizum
  Efectivo
  Tarjeta
  Transferencia
  Metalico
}

' Relaciones arquitectónicas
TipoDeporte "1" <-- "*" Pista : contiene >
Pista "1" <-- "*" PistaReservada : historial >
Reserva "1" <-- "*" PistaReservada : desglose >
Reserva .> MetodoPago : usa >

@enduml